const mongoose = require('mongoose')
const {ObjectId} = mongoose.Schema.Types
const MarkSheet = new mongoose.Schema({
    markSheet:[{
        english:{
            type:String,
            default:0
        },
        urdu:{
            type:Number,
            default:0
        },
        urduStatus:{
            type:String,
            default:""
        },
        islamyat:{
            type:String,
            default:0
        },
        islamyatStatus:{
            type:String,
            default:""
        },
        mathStatus:{
            type:String,
            default:"noting"
        },
        chemistyStatus:{
            type:String,
            default:"noting"
        },
        bioStatus:{
            type:String,
            default:"noting"
        },
        physicsStatus:{
            type:String,
            default:"noting"
        },
        englishStatus:{
            type:String,
            default:"noting"
        },
        chemistry:{
            type:String,
            default:0
        },
        biology:{
            type:String,
            default:0
        },
        math:{
            type:String,
            default:0
        },
        physics:{
            type:Number,
            default:0
        },
        total:{
            type:Number,
            default:0
        },
        percentage:{
            type:Number,
            default:0
        },
        obtainMarks:{
            type:Number,
            default:0
        },
        grade:{
            type:String,
            default:0
        }
    }],
    studentId:{
       type:ObjectId,
       ref:"Students"
    }
},{timestamps:true})

mongoose.model("MarkSheets",MarkSheet)