const mongoose = require('mongoose')
const {ObjectId} = mongoose.Schema.Types
const postSchema = new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    fatherName:{
        type:String,
        required:true
    },
    cell:{
        type:Number,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    course:{
        type:String,
        required:true
    },
    inClass:{
        type:String,
        required:true
    },
    photo:{
        type:String,
        required:true
    },
   
    rollNumber:{
        type:Number,
        required:true
    },
    fee:[{
        month:{
            type:String,
            default:""
        },
        paid:{
            type:Number,
            default:0
        },
        remaining:{
            type:Number,
            default:0
        },
        status:{
            type:String,
            default:false
        },
        totalFee:{
            type:Number
        }
    }],
    postedBy:{
       type:ObjectId,
       ref:"User"
    }
},{timestamps:true})

mongoose.model("Students",postSchema)